//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHASE_END_PROJECT_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHASE_END_PROJECT_3Entities : DbContext
    {
        public PHASE_END_PROJECT_3Entities()
            : base("name=PHASE_END_PROJECT_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustLogInfo> CustLogInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
